---
pull_request_rules:
  - actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success~=^Test CrateDB SQL on windows
      - status-success=docs/readthedocs.org:crate-docs
    name: default
