---
pull_request_rules:
  - actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success~=Build docs on ubuntu-latest using Python 3.7
      - status-success~=Build docs on ubuntu-latest using Python 3.8
      - status-success~=Build docs on ubuntu-latest using Python 3.9
      - status-success~=Build docs on macos-latest using Python 3.7
      - status-success~=Build docs on macos-latest using Python 3.8
      - status-success~=Build docs on macos-latest using Python 3.9
      - status-success~=docs/readthedocs.org
    name: default
  - name: Delete branch after merge
    actions:
      delete_head_branch: {}
    conditions:
      - merged
